CREATE DATABASE IF NOT EXISTS property;
CREATE DATABASE IF NOT EXISTS ari;
CREATE DATABASE IF NOT EXISTS booking;
CREATE DATABASE IF NOT EXISTS payment;
CREATE DATABASE IF NOT EXISTS coupon;
CREATE DATABASE IF NOT EXISTS membership;
CREATE DATABASE IF NOT EXISTS search;
